### ISSUE TITLE
[Bug] 插件无法滚动导致配置项无法完全显示

### ISSUE THREAD

**Issue by laoboxie** [d-w-x/picgo-plugin-gitlab-files#2]
# Issue Reoprt

## Describe

picgo 2.2.2 安装此插件无法向下滚动，导致配置项展示不全，无法进行设置。
picgo客户端也无法拉伸窗口让配置选项展示全。
目前的解决方法是按“tab”键来进行跳转下一个选项。

## Reproduce

1. 点击“图床设置”
2. 点击“gitlab files 图片上传”插件
3. 无法滚动

## Expected

至少能够滚动，能下滑展示全部的选项。

## Screenshots

![image](https://user-images.githubusercontent.com/23701019/111097732-0a96e700-857d-11eb-9423-42ff75e76a50.png)

## Environment

- OS: mac
- CLI or GUI：GUI
- Plugin version(本插件的版本)：1.1.4

**Comment by d-w-x** [comment]
您好：
这个问题很可能是picgo本身的UI显示问题，下午我去那边仓库看下情况。
这个UI插件本身只提供参数，并不参与页面的绘制。

**Comment by d-w-x** [comment]
您好:
  根据测试,在最新的 PicGo 中此问题已经被修复,等待他们发布最新的版本后,这里可以使用滚轮切换.

**Comment by laoboxie** [comment]
> 您好:
> 根据测试,在最新的 PicGo 中此问题已经被修复,等待他们发布最新的版本后,这里可以使用滚轮切换.

好的，谢谢！
