### ISSUE TITLE
[Bug] Gitlab 版本低于 13 引起的图片路径错误

### ISSUE THREAD

**Issue by laoboxie** [d-w-x/picgo-plugin-gitlab-files#3]
# Issue Reoprt

## Describe

上传图片后，路径中如 `http://gitlab.com/xxx/img-bed/-/raw/master/pictures/avatar_202103151174.jpeg`，但是中间有“-/raw”，导致图片显示失败。
在去掉“-/”后，图片才能正常显示

## Reproduce

1. 上传图片
2. 黏贴版中获得链接
3. 图片链接无法显示

## Expected

图片链接中可以去掉“-/”，图片能正常显示。

## Environment

**Desktop (please complete the following information):**
 - OS: mac
- CLI or GUI： gui
- Plugin version(本插件的版本)：1.1.4

**Comment by d-w-x** [comment]
您好
请问你使用的是 gitlab.com 还是自建的gitlab？
您的图片上传的是哪个分支？
如果是自建的话能否提供下 gitlab 版本信息？

**Comment by laoboxie** [comment]
使用的是自建的gitlab，GitLab Community Edition 12.5.4。
上传的是maste分支。
看起来是gitlab的路径不同版本是不一致的，希望能够兼容不同版本，或许提供一个配置项来配置。
参考链接：https://github.com/italia/publiccode-parser-go/issues/40

**Comment by d-w-x** [comment]
最新版本已经更新,

- 由于 gitlab 的 version api 需要**用户的 api 权限**, **仓库 api 权限**无法读取, 根据权限最小要求, 这里没有采用 api 请求的方式.
- 提供一个兼容参数, 设置为 true 会开启对低版本 gitlab 的兼容.
  - 默认此选项是 false ,即开启高版本模式.
  - 需要自己修改之前上传图片的路径,之后图片不需要修改
  - 由于我使用的 gitlab 高于此版本,如果有其他问题可以继续补充.

**Comment by laoboxie** [comment]
> 最新版本已经更新,
> 
> * 由于 gitlab 的 version api 需要**用户的 api 权限**, **仓库 api 权限**无法读取, 根据权限最小要求, 这里没有采用 api 请求的方式.
> * 提供一个兼容参数, 设置为 true 会开启对低版本 gitlab 的兼容.
>   
>   * 默认此选项是 false ,即开启高版本模式.
>   * 需要自己修改之前上传图片的路径,之后图片不需要修改
>   * 由于我使用的 gitlab 高于此版本,如果有其他问题可以继续补充.
经测试，功能正常。感谢及时处理！

**Comment by laoboxie** [comment]
> 最新版本已经更新,
> 
> * 由于 gitlab 的 version api 需要**用户的 api 权限**, **仓库 api 权限**无法读取, 根据权限最小要求, 这里没有采用 api 请求的方式.
> * 提供一个兼容参数, 设置为 true 会开启对低版本 gitlab 的兼容.
>   
>   * 默认此选项是 false ,即开启高版本模式.
>   * 需要自己修改之前上传图片的路径,之后图片不需要修改
>   * 由于我使用的 gitlab 高于此版本,如果有其他问题可以继续补充.

经测试，功能正常。感谢及时处理！
