### ISSUE TITLE
上传失败，用的是极狐，另一个gitlab插件就可以，报错

### ISSUE THREAD

**Issue by HYLCWR** [d-w-x/picgo-plugin-gitlab-files#4]
报错为：
TypeError: Cannot read property 'split' of null
    at Object.formatPath (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-gitlab-files\dist\utils\pathUtils.js:39:23)
    at C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-gitlab-files\dist\index.js:136:42
    at Array.forEach (<anonymous>)
    at Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-gitlab-files\dist\index.js:135:17)
    at Lifecycle.doUpload (C:\PicGo\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:77)
    at Lifecycle.start (C:\PicGo\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:24)
    at async PicGo.upload (C:\PicGo\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\PicGo\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (C:\PicGo\PicGo\resources\app.asar\background.js:36:31625)

**Comment by d-w-x** [comment]
请问是 极狐 哪个版本？方便给个测试链接吗？

**Comment by HYLCWR** [comment]
我也不知道是哪个版本呢，







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "d-w-x/picgo-plugin-gitlab-files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [d-w-x/picgo-plugin-gitlab-files] 上传失败，用的是极狐，另一个gitlab插件就可以，报错 (Issue #4)





 
请问是 极狐 哪个版本？方便给个测试链接吗？

**Comment by d-w-x** [comment]
网址呢？官方的还是自己搭建的？

**Comment by d-w-x** [comment]
https://[url]/help  页面可以看到版本，我在 `JiHu GitLab 15.0.1-jh` 命令行测试没有问题哎？

**Comment by HYLCWR** [comment]
https://jihulab.com/HYLCWR/imgbed
就是自己新建的仓库，我是小白，picgo版本是2.3

报错信息如下：
https://jihulab.com/HYLCWR/imgbed




&nbsp;StatusCodeError: 401 - "{\"message\":\"401 Unauthorized\"}"
&nbsp; &nbsp; at new StatusCodeError (C:\PicGo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
&nbsp; &nbsp; at Request.plumbing.callback (C:\PicGo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
&nbsp; &nbsp; at Request.RP$callback [as _callback] (C:\PicGo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
&nbsp; &nbsp; at Request.self.callback (C:\PicGo\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
&nbsp; &nbsp; at Request.emit (events.js:200:13)
&nbsp; &nbsp; at Request.<anonymous&gt; (C:\PicGo\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
&nbsp; &nbsp; at Request.emit (events.js:200:13)
&nbsp; &nbsp; at IncomingMessage.<anonymous&gt; (C:\PicGo\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
&nbsp; &nbsp; at Object.onceWrapper (events.js:288:20)
&nbsp; &nbsp; at IncomingMessage.emit (events.js:205:15)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "d-w-x/picgo-plugin-gitlab-files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [d-w-x/picgo-plugin-gitlab-files] 上传失败，用的是极狐，另一个gitlab插件就可以，报错 (Issue #4)





 
网址呢？官方的还是自己搭建的？

**Comment by d-w-x** [comment]
访问令牌在这里申请： https://jihulab.com/-/profile/personal_access_tokens  
![image](https://user-images.githubusercontent.com/35656321/172662665-b74a9417-cc23-4ee7-837d-f8b250a0ac0b.png)

https://jihulab.com/d-w-x/imagebad
我这边也测试成功了？

**Comment by d-w-x** [comment]
![image](https://user-images.githubusercontent.com/35656321/172663799-10a6b5bd-86d3-409d-867b-483f8208da21.png)

如果还是不可以，截图一下你这里的配置文件？（记得关键信息打码）

**Comment by HYLCWR** [comment]
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月9日(星期四) 凌晨0:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [d-w-x/picgo-plugin-gitlab-files] 上传失败，用的是极狐，另一个gitlab插件就可以，报错 (Issue #4)





 

 
如果还是不可以，截图一下你这里的配置文件？（记得关键信息打码）

**Comment by d-w-x** [comment]
![image](https://user-images.githubusercontent.com/35656321/172665696-59df94a3-5328-45db-9226-72f5729ce304.png)
如果是 GUI 的话截图这里的配置；

![image](https://user-images.githubusercontent.com/35656321/172665774-13cbf0c2-ac6b-4bc9-987d-b2e13a41dfdb.png)
你的上一条回复我看见是空白，方便的话还是直接在 github 回复吧。

**Comment by HYLCWR** [comment]
![image](https://user-images.githubusercontent.com/72905028/172666276-9f0c35d2-df09-4aeb-8d26-997d75b1235a.png)

**Comment by HYLCWR** [comment]
> 

![image](https://user-images.githubusercontent.com/72905028/172667322-595ebf1c-8db9-4b88-b1b5-d90d4230ea48.png)

**Comment by d-w-x** [comment]
![image](https://user-images.githubusercontent.com/35656321/172667514-20a8eb35-2bf6-48b2-8948-3405c0a3cab7.png)
这里日志文件呢？

**Comment by HYLCWR** [comment]
> 

------Error Stack Begin------
StatusCodeError: 400 - {"error":"commit_message is empty"}
    at new StatusCodeError (C:\PicGo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\PicGo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\PicGo\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\PicGo\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (C:\PicGo\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (C:\PicGo\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-06-09 00:21:40 [PicGo ERROR] ======End Gitlab files Error====== 
2022-06-09 00:21:40 [PicGo INFO] afterUploadPlugins: autobackup running 
2022-06-09 00:21:40 [PicGo SUCCESS] 
 
2022-06-09 00:21:40 [PicGo ERROR] startup error
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'Autobackup/mark.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.writeFileSync (fs.js:1206:35)
    at ReadFileContext.callback (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-autobackup\src\index.js:110:24)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
-------Error Stack End-------

**Comment by d-w-x** [comment]
稍后，我看看哈。

**Comment by d-w-x** [comment]
更新了一个版本你试试；
由于国内镜像源还没来得及同步，记得把这里先改回官方：
![image](https://user-images.githubusercontent.com/35656321/172673763-73af90bb-70e9-4e46-b9c9-7ec9c5fa037e.png)

https://registry.npmjs.org ，然后选更新，应该就能到 1.1.6

**Comment by HYLCWR** [comment]
> 更新了一个版本你试试； 由于国内镜像源还没来得及同步，记得把这里先改回官方： ![image](https://user-images.githubusercontent.com/35656321/172673763-73af90bb-70e9-4e46-b9c9-7ec9c5fa037e.png)
> 
> https://registry.npmjs.org ，然后选更新，应该就能到 1.1.6

牛逼，可以了，一切正常

**Comment by d-w-x** [comment]
ok，那就行。
刚才主要是不知道为什么你的这里，非必填选项的默认文本给没有了：
![image](https://user-images.githubusercontent.com/35656321/172676548-bac14f3e-cceb-4631-9395-0cc59677e759.png)
然后插件获取出现问题了，现在我加上了默认值应该就好了。

**Comment by HYLCWR** [comment]
> 

牛逼老哥辛苦了，给个WeChat吧，请你喝杯小咖啡

**Comment by d-w-x** [comment]
感谢，不过不用了，我也是自己在用（虽然也不会空这么多倒是）。

早点休息吧哈哈哈。

**Comment by HYLCWR** [comment]
> 谢谢，不过不用了，我也是自己在用（虽然也不会空这么多倒是）。
> 
> 早点休息吧哈哈哈。

再次感谢，gitlab不支持webp格式吗？

**Comment by HYLCWR** [comment]
勾哪一个？第一个api就行了?
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月8日(星期三) 晚上11:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [d-w-x/picgo-plugin-gitlab-files] 上传失败，用的是极狐，另一个gitlab插件就可以，报错 (Issue #4)





 
访问令牌在这里申请： https://jihulab.com/-/profile/personal_access_tokens
 
 
https://jihulab.com/d-w-x/imagebad
 我这边也测试成功了？

**Comment by d-w-x** [comment]
对的，api 就行。

**Comment by HYLCWR** [comment]
&nbsp;是不是我的token的问题？我用的是个人的token，需要打钩的部分全都打了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "d-w-x/picgo-plugin-gitlab-files"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [d-w-x/picgo-plugin-gitlab-files] 上传失败，用的是极狐，另一个gitlab插件就可以，报错 (Issue #4)





 
https://[url]/help  页面可以看到版本，我在 JiHu GitLab 15.0.1-jh 命令行测试没有问题哎？

**Comment by d-w-x** [comment]
我还是看不到你的图片？请提供图片呢？

**Comment by lucasjinreal** [comment]
我无语了啊

<img width="464" alt="image" src="https://user-images.githubusercontent.com/21303438/224480528-fb92ba96-bd67-4bb6-b9e2-6f01b7ad0729.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/21303438/224480536-43cf712f-f5c2-4d0b-bfb0-62d4326a5a50.png">


我感觉收到了欺骗，这怎么搞，更新了要重启了，没用，老版本确实无法上传，老师报错

**Comment by jinfagang** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/21303438/224480634-ff188b89-09be-40c8-a9a8-7b424c8a2465.png">

这完全不行啊

<img width="876" alt="image" src="https://user-images.githubusercontent.com/21303438/224480647-99fa8bf9-d7a7-4dd8-a1e7-f9378f75fd67.png">

**Comment by d-w-x** [comment]
请重新开启一个 issue 并填写相关信息。

注意将 token 打码。

**Comment by lucasjinreal** [comment]
?????

**Comment by lucasjinreal** [comment]
这是同一个问题。。。。。。

**Comment by d-w-x** [comment]
这个是别人提出的 issue，你在这里回复，他同样会收到邮件提示，这可能并不是他需要的。

问题的表象一样，也并不意味着可以用同样的方法解决。
