### ISSUE TITLE
[Other ]关于插件适配 picgo-core v1.5.0 的请教

### ISSUE THREAD

**Issue by W4J1e** [d-w-x/picgo-plugin-gitlab-files#6]
开发者你好，很抱歉在你的项目 issue 里打扰到你。
我此前改了一个s3的插件，用来适配上传图片到多吉云。后来经过另一位开发者的帮助，重写了获取`sessionToken`这一部分，使插件使用更方便。
在picgo-core更新到1.5.0以上之后，插件便无法正常使用。我把插件中原本由`request`获取的请求按照`axios`的示例做了修改，并根据`vscode`提示的问题修改了个别地方的代码。但我本身不是开发者（技术能力实在不忍直视），加上那一部分代码不是我写的，所以修改之后在本地测试仍然无法正常上传。
因此前来学习，参考了你的更新和 issue 里的解释，还是有些不太明白。如果大佬有空的话，恳请指点一二或者帮忙修改一下，如果有需要我补充的信息请随时联系我。
最后，方便的话我请你喝杯咖啡，谢谢。
插件地址：https://github.com/W4J1e/picgo-plugin-dogecloud

**Comment by d-w-x** [comment]
我没用过 多吉云，没有账号哎。

**Comment by W4J1e** [comment]
> 我没用过 多吉云，没有账号哎。

我手头也没有其它的测试账号，方便的话可以加个QQ吗？

**Comment by d-w-x** [comment]
1666287538
