### ISSUE TITLE
[Other] 自建 Gitlab 服务器使用非标准端口，需要修改 Gitlab 服务器对应配置

### ISSUE THREAD

**Issue by yuzaii** [d-w-x/picgo-plugin-gitlab-files#7]
# Issue Reoprt

## Describe
自己搭建的gitlab的地址带有端口，能够上传成功但是返回的图片地址却没有端口显示，请问这是插件问题还是picgo的问题

![image](https://user-images.githubusercontent.com/82126539/221132963-e7710a1f-908e-41b7-bbf2-0ff1eebb85a4.png)
![image](https://user-images.githubusercontent.com/82126539/221132988-f4c61966-5215-4e02-a05a-f8ae4735c8fa.png)

**Comment by d-w-x** [comment]
请访问 `http://192.168.105.130:8089/api/v4/projects` 截图返回值呢？

**Comment by yuzaii** [comment]
我看了一下好像接口jiu'mei'y就没有端口
![image](https://user-images.githubusercontent.com/82126539/221398241-74da4d2e-eb3e-4db0-b483-5eda85c25aa2.png)

**Comment by yuzaii** [comment]
请问 这个有什么办法解决吗

**Comment by d-w-x** [comment]
请参考[这个官方文档](https://docs.gitlab.com/omnibus/settings/configuration.html)。

**Comment by yuzaii** [comment]
十分感谢
