### ISSUE TITLE
上传错误[Bug] 问题

### ISSUE THREAD

**Issue by laihandong** [d-w-x/picgo-plugin-gitlab-files#8]
# Issue Reoprt

## Describe
“文件名及其路径”仅设置为"{fileName}"时有效，若在前加上任意路径，则会导致上传失败（失败日志放在下面↓）

## Reproduce
1. 安装picgo - 2.3.1
2. xxx/Roaming/picgo目录下 npm install picgo-plugin-gitlab-files （显示安装的picgo-plugin-gitlab-files@1.2.2）
3. 填写上传设置
    3.1 服务器地址： 公司内网搭建的地址
    3.2 id：                 自己某公共库项目的id
    3.3 分支：            master
    3.4 token              已勾选全部权限，且永久生效
    3.5 自托管的gitlab...：true
    3.6 文件名机器路径：/pictures/{fileName} （库中根目录下已存在pictures目录）
    ....（剩下的保持默认）
4. 拖拽上传图片
    图片名为test.png
6. See error

## Expected
上传至库的/pictures/下面

## Screenshots
**Screenshots(合适数量的截图,关键信息适当打码)**

## Environment
os：windows
npm -v：6.4.1
node -v：8.12.0

## Log
```txt
2023-03-10 08:53:52 [PicGo INFO] Before transform 
2023-03-10 08:53:52 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-10 08:53:52 [PicGo INFO] Before upload 
2023-03-10 08:53:52 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-10 08:53:52 [PicGo INFO] Uploading... Current uploader is [gitlab-files-uploader] 
2023-03-10 08:53:53 [PicGo ERROR] ======Start Gitlab files Upload Error====== 
2023-03-10 08:53:53 [PicGo ERROR] {
  "method": "POST",
  "url": "http://xxx自建地址xxx/api/v4/projects/586/repository/files/%2Fpicture%2Ftest.png",
  "statusCode": 404,
  "message": "Request failed with status code 404",
  "stack": {},
  "response": {
    "status": 404,
    "statusCode": 404,
    "body": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /api/v4/projects/586/repository/files/pictures/test.png was not found on this server.</p>\n<p>Additionally, a 404 Not Found\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n"
  }
} 
2023-03-10 08:53:53 [PicGo ERROR] ======End Gitlab files Error====== 
2023-03-10 08:53:53 [PicGo SUCCESS] 
```

## Additional
**Additional information(其他信息)**
picgo中，若仅将上传路径改为{fileName}，则能上传成功。

同样的设置，使用typora中“偏好设置-图像-验证图片上传选项”来测试上传，`/pictures/{fileName}  和 {fileName}`均能成功

**Comment by d-w-x** [comment]
请检查公司是否使用了 nginx 等 web server 反向代理了 gitlab，使得 `http://[gitlab]/api/v4` 无法访问。

如果配置没有问题的话，浏览器可以直接打开此页面并返回当前用户可见的所有仓库：
`https://gitlab.com/api/v4/projects`

**Comment by laihandong** [comment]
> https://github.com/d-w-x/picgo-plugin-gitlab-files/issues/8#issuecomment-1463132425

浏览器直接访问`https://gitlab.com/api/v4/projects`是成功的，可以看见所有仓库的信息

**Comment by d-w-x** [comment]
`gitlab.com` 换成你们公司的仓库地址后还可以看到吗？

**Comment by laihandong** [comment]
> `gitlab.com` 换成你们公司的仓库地址后还可以看到吗？

可以看得到的

**Comment by d-w-x** [comment]
`http://xxx自建地址xxx/api/v4/projects/586/` 打开有内容吗？

**Comment by laihandong** [comment]
> https://github.com/d-w-x/picgo-plugin-gitlab-files/issues/8#issuecomment-1463201318
也有的

**Comment by d-w-x** [comment]
这个问题我无法进一步复现，在 gitlab、自建的 gitlab、极狐都可以正常设置路径。

并且如果 gitlab api 发生错误，返回的信息应该是 json 信息而不是 `<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">`。

此问题你可能需要和贵公司 gitlab 维护人员进行进一步确认。

**Comment by laihandong** [comment]
即时上传的url为“xxxx/files/%2Fpicture%2Ftest.png"也能上传成功吗？
我有点认为是斜杠转译为"%2F"后导致api无法识别

**Comment by d-w-x** [comment]
请参考[官方 API](https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository)。

**Comment by laihandong** [comment]
> https://github.com/d-w-x/picgo-plugin-gitlab-files/issues/8#issuecomment-1463205251
好的，谢谢。
我先去咨询一下公司有关的负责人
